In [1473]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import pandas_datareader as pdr
import seaborn as sns
import talib 
from sklearn.preprocessing import MinMaxScaler
from sklearn import tree
from sklearn.linear_model import LinearRegression
from sklearn.feature_selection import RFE
from mlxtend.feature_selection import SequentialFeatureSelector as SFS



In [1474]:
startdate = '2016-01-1'
enddate= '2021-12-31'
scaler = MinMaxScaler()

In [1475]:
dji = pdr.get_data_yahoo('^DJI', start=startdate, end=enddate)
dji_norm = pd.DataFrame(scaler.fit_transform(dji), columns=dji.columns)
n225 = pdr.get_data_yahoo("^N225", start=startdate, end=enddate)
n225_norm = pd.DataFrame(scaler.fit_transform(n225), columns=n225.columns)
hsi = pdr.get_data_yahoo("^HSI", start=startdate, end=enddate)
hsi_norm = pd.DataFrame(scaler.fit_transform(hsi), columns=hsi.columns)
sse = pdr.get_data_yahoo("000001.SS", start=startdate, end=enddate)
sse_norm = pd.DataFrame(scaler.fit_transform(sse), columns=sse.columns)


<h1>Dow Jones Industrial Average</h1>

<h2>Feature Selection</h2>

In [1476]:
dji['Future Close'] = dji['Close'].shift(-1)
dji

High           Low          Open         Close     Volume  \
Date                                                                            
2015-12-31  17590.660156  17421.160156  17590.660156  17425.029297   93690000   
2016-01-04  17405.480469  16957.630859  17405.480469  17148.939453  148060000   
2016-01-05  17195.839844  17038.609375  17147.500000  17158.660156  105750000   
2016-01-06  17154.830078  16817.619141  17154.830078  16906.509766  120250000   
2016-01-07  16888.359375  16463.630859  16888.359375  16514.099609  176240000   
...                  ...           ...           ...           ...        ...   
2021-11-17  36159.699219  35909.480469  36159.699219  35931.050781  358310000   
2021-11-18  35952.628906  35654.390625  35901.691406  35870.949219  435080000   
2021-11-19  35879.089844  35555.371094  35879.089844  35601.980469  408840000   
2021-11-22  35929.660156  35615.550781  35631.410156  35619.250000  420810000   
2021-11-23  35762.351562  35542.871094  35619.921875  35615.550781  186011219   

               Adj Close  Future Close  
Date                                    
2015-12-31  17425.029297  17148.939453  
2016-01-04  17148.939453  17158.660156  
2016-01-05  17158.660156  16906.509766  
2016-01-06  16906.509766  16514.099609  
2016-01-07  16514.099609  16346.450195  
...                  ...           ...  
2021-11-17  35931.050781  35870.949219  
2021-11-18  35870.949219  35601.980469  
2021-11-19  35601.980469  35619.250000  
2021-11-22  35619.250000  35615.550781  
2021-11-23  35615.550781           NaN  

[1486 rows x 7 columns]

In [1477]:
def computeTarget(present_price, future_price):
    score = (( future_price - present_price ) / present_price ) * 100
    target = []
    for i in score:
        if i > 0.1:
            target.append(1)
        else:
            target.append(0)
    return target
# 1 = up, 0 = down

In [1478]:

target = computeTarget(dji['Close'], dji['Future Close'])

dji['Target'] = target


In [1479]:
dji_target = dji.tail(1)
dji_target
dji = dji.dropna()

In [1480]:
close = dji['Close']
high = dji['High']
low = dji['Low']
open = dji['Open']
volume  = dji['Volume']

In [1481]:
dji_ti = pd.DataFrame()
dji_ti['SMA20'] = talib.SMA(close, timeperiod=20)
dji_ti['SMA50'] = talib.SMA(close, timeperiod=50)
dji_ti['SMA200'] = talib.SMA(close, timeperiod=200)
dji_ti['EMA'] = talib.EMA(close, timeperiod=14)
dji_ti['OBV'] = talib.OBV(close, volume)
dji_ti['RSI14'] = talib.RSI(close, timeperiod=14)
dji_ti['ADX'] = talib.ADX(high, low, close, timeperiod=14)
dji_ti['ADXR'] = talib.ADXR(high, low, close, timeperiod=14)
dji_ti['aroondown'], dji_ti['aroonup'] = talib.AROON(high, low, timeperiod=14)
dji_ti['APO'] = talib.APO(close, fastperiod=12, slowperiod=26, matype=0)
dji_ti['AROONOSC'] = talib.AROONOSC(high, low, timeperiod=14)
dji_ti['BOP'] = talib.BOP(open, high, low, close)
dji_ti['CCI'] = talib.CCI(high, low, close, timeperiod=14)
dji_ti['CMO'] = talib.CMO(close, timeperiod=14)
dji_ti['DX'] = talib.DX(high, low, close, timeperiod=14)
dji_ti['macd'],dji_ti['macdsignal'],dji_ti['macdhist'] = talib.MACD(close, fastperiod = 12, slowperiod=26, signalperiod=9)
dji_ti['MFI'] = talib.MFI(high, low, close, volume, timeperiod=14)
dji_ti['MINUS_DI'] = talib.MINUS_DI(high, low, close, timeperiod=14)
dji_ti['MINUS_DM'] = talib.MINUS_DM(high, low, timeperiod=14)
dji_ti['MOM'] = talib.MOM(close, timeperiod=14)
dji_ti['PLUS_DI'] = talib.PLUS_DI(high, low, close, timeperiod=14)
dji_ti['PLUS_DM'] = talib.PLUS_DM(high, low, timeperiod=14)
dji_ti['PPO'] = talib.PPO(close, fastperiod=12, slowperiod=26, matype=0)
dji_ti['ROC'] = talib.ROC(close, timeperiod=10)
dji_ti['ROCP'] = talib.ROCP(close, timeperiod=10)
dji_ti['ROCR'] = talib.ROCR(close, timeperiod=10)
dji_ti['ROCR100'] = talib.ROCR100(close, timeperiod=10)
dji_ti['slowk'], dji_ti['slowd'] = talib.STOCH(high, low, close, fastk_period=5, slowk_period=3, slowd_period=3, slowd_matype=0)
dji_ti['fastk'], dji_ti['fastd'] = talib.STOCHF(high, low, close, fastk_period=5, fastd_period=3, fastd_matype=0)
dji_ti['TRIX'] = talib.TRIX(close, timeperiod=30)
dji_ti['ULTOSC'] = talib.ULTOSC(high, low, close, timeperiod1=7, timeperiod2=14, timeperiod3=28)
dji_ti['WILLR'] = talib.WILLR(high, low, close, timeperiod=14)
dji_ti['Target'] = dji['Target']
dji_ti

SMA20         SMA50        SMA200           EMA  \
Date                                                                 
2015-12-31           NaN           NaN           NaN           NaN   
2016-01-04           NaN           NaN           NaN           NaN   
2016-01-05           NaN           NaN           NaN           NaN   
2016-01-06           NaN           NaN           NaN           NaN   
2016-01-07           NaN           NaN           NaN           NaN   
...                  ...           ...           ...           ...   
2021-11-16  35954.388477  35141.137109  34160.790791  36004.355982   
2021-11-17  35970.474023  35159.136719  34186.828047  35994.581955   
2021-11-18  35983.867578  35178.968125  34210.903496  35978.097590   
2021-11-19  35980.115625  35198.853359  34233.172197  35927.948641   
2021-11-22  35974.020703  35213.845781  34254.339648  35886.788822   

                     OBV      RSI14        ADX       ADXR   aroondown  \
Date                                                                    
2015-12-31  9.369000e+07        NaN        NaN        NaN         NaN   
2016-01-04 -5.437000e+07        NaN        NaN        NaN         NaN   
2016-01-05  5.138000e+07        NaN        NaN        NaN         NaN   
2016-01-06 -6.887000e+07        NaN        NaN        NaN         NaN   
2016-01-07 -2.451100e+08        NaN        NaN        NaN         NaN   
...                  ...        ...        ...        ...         ...   
2021-11-16  4.068477e+10  60.821001  23.921669  22.839573    0.000000   
2021-11-17  4.032646e+10  54.656278  23.134882  22.278214    0.000000   
2021-11-18  3.989138e+10  53.009423  21.616344  21.578782    0.000000   
2021-11-19  3.948254e+10  46.287684  20.569966  21.215418  100.000000   
2021-11-22  3.990335e+10  46.754531  19.386325  20.889122   92.857143   

              aroonup  ...      ROCR     ROCR100      slowk      slowd  \
Date                   ...                                               
2015-12-31        NaN  ...       NaN         NaN        NaN        NaN   
2016-01-04        NaN  ...       NaN         NaN        NaN        NaN   
2016-01-05        NaN  ...       NaN         NaN        NaN        NaN   
2016-01-06        NaN  ...       NaN         NaN        NaN        NaN   
2016-01-07        NaN  ...       NaN         NaN        NaN        NaN   
...               ...  ...       ...         ...        ...        ...   
2021-11-16  57.142857  ...  1.002485  100.248497  38.460274  24.951303   
2021-11-17  50.000000  ...  0.993735   99.373500  30.743867  30.143858   
2021-11-18  42.857143  ...  0.992989   99.298860  30.205023  33.136388   
2021-11-19  35.714286  ...  0.980016   98.001625  14.707654  25.218848   
2021-11-22  28.571429  ...  0.977685   97.768544  15.738752  20.217143   

                fastk      fastd      TRIX     ULTOSC      WILLR  Target  
Date                                                                      
2015-12-31        NaN        NaN       NaN        NaN        NaN       0  
2016-01-04        NaN        NaN       NaN        NaN        NaN       0  
2016-01-05        NaN        NaN       NaN        NaN        NaN       0  
2016-01-06        NaN        NaN       NaN        NaN        NaN       0  
2016-01-07        NaN        NaN       NaN        NaN        NaN       0  
...               ...        ...       ...        ...        ...     ...  
2021-11-16  52.614944  38.460274  0.051693  45.702226 -41.507722       0  
2021-11-17   5.298153  30.743867  0.054180  40.768597 -68.059884       0  
2021-11-18  32.701973  30.205023  0.056254  43.144530 -76.237339       0  
2021-11-19   6.122836  14.707654  0.057744  41.457206 -95.386852       0  
2021-11-22   8.391447  15.738752  0.058735  38.329353 -93.677605       0  

[1485 rows x 38 columns]

In [1482]:
# plt.figure(figsize=(12,10))
# cor = ti.corr()
# sns.heatmap(cor, annot=True, cmap=plt.cm.Reds)
# plt.show()

In [1483]:
# cor_target = abs(cor["Target"])
# features = cor_target[cor_target>0.05]
# features

In [1484]:
dji_ti = dji_ti.dropna()
X = dji_ti.drop("Target", axis=1)  # Feature Matrix
y = dji_ti["Target"]               # Target Variable
y

Date
2016-10-14    0
2016-10-17    1
2016-10-18    1
2016-10-19    0
2016-10-20    0
             ..
2021-11-16    0
2021-11-17    0
2021-11-18    0
2021-11-19    0
2021-11-22    0
Name: Target, Length: 1286, dtype: int64

In [1485]:
X = X.fillna(0)

In [1486]:
#X.isna().sum()

In [1568]:
def selectFeatures(df):
    #Split the features and target data
    #select the first 13 columns as features
    X = df.drop("Target", axis=1)  # Feature Matrix
    #Select the last column for target 
    Y = df["Target"]               # Target Variable

    #Build a logistic regression model 
    model = LinearRegression()
    #Define RFE 
    rfe = RFE(model)
    #Use RFE to select the top 5 features 
    fit = rfe.fit(X, Y)

    #Create a dataframe for the results 
    df_RFE_results = []
    for i in range(X.shape[1]):
        df_RFE_results.append(
            {      
                'Feature_names': X.columns[i],
                'Selected':  rfe.support_[i],
                'RFE_ranking':  rfe.ranking_[i],
            }
        )

    df_RFE_results = pd.DataFrame(df_RFE_results)
    df_RFE_results.index.name='Columns'
    ti = []
    for index, row in df_RFE_results.iterrows():
        if row['Selected'] == True:
            ti.append(row['Feature_names']) 
    return ti

In [1584]:
dji_features = selectFeatures(dji_ti)
dji_features

['RSI14',
 'ADX',
 'ADXR',
 'aroondown',
 'BOP',
 'CCI',
 'CMO',
 'DX',
 'macd',
 'macdsignal',
 'PLUS_DI',
 'ROC',
 'ROCR100',
 'slowd',
 'fastk',
 'TRIX',
 'ULTOSC',
 'WILLR']

In [1585]:
from sklearn.model_selection import train_test_split
X = dji_ti.loc[:, dji_features].values
#X = dji_ti.loc[:, ['CCI', 'DX', 'MINUS_DI', 'PLUS_DM', 'slowd']].values
y = dji_ti.loc[:, ['Target']].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [1586]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [1587]:
# Visualize the data
#
def visualize(title, xlabel, ylabel, classifier, X_test, y_test):
    X_set, y_set = X_test, y_test
    X1, X2 = np.meshgrid(np.arange(start = X_set[:, 0].min() - 1, stop = X_set[:, 0].max() + 1, step = 0.01),
                         np.arange(start = X_set[:, 1].min() - 1, stop = X_set[:, 1].max() + 1, step = 0.01))
    plt.contourf(X1, X2, classifier.predict(np.array([X1.ravel(), X2.ravel()]).T).reshape(X1.shape),
                 alpha = 0.75, cmap = ListedColormap(('lightblue', 'cornsilk')))
    plt.xlim(X1.min(), X1.max())
    plt.ylim(X2.min(), X2.max())

    for i, j in enumerate(np.unique(y_set)):
        plt.scatter(X_set[y_set == j, 0], X_set[y_set == j, 1], label = j)

    plt.title(title)
    plt.xlabel(xlabel)
    plt.ylabel(ylabel)
    plt.legend()
    plt.show()

<h2>Decision Tree</h2>

In [1588]:
# Decision Tree Classifier: Create and Train the model
#
from sklearn.tree import DecisionTreeClassifier

dtc = DecisionTreeClassifier()
dtc.fit(X_train, y_train)

DecisionTreeClassifier()

In [1589]:
# Prediction
#
y_pred = dtc.predict(X_test)  #Accuracy
y_pred

array([0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1])

In [1590]:
# Look at the actual y_test
#
y_test

array([[0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
    

In [1591]:
# See the accuracy
#
from sklearn import metrics
print('Accuracy Score:', metrics.accuracy_score(y_test, y_pred))

Accuracy Score: 0.43023255813953487


In [1551]:
# See the confusion matrix
#
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[61, 69],
       [50, 78]])

<h2>Random Forest</h2>

<h2>Logistic Regression</h2>

<h2>XGBoost</h2>

<h2>Linear Regression</h2>

<h2>Gauccian Process Regress</h2>

<h1>Nikkei 225 Stock Average</h1>

<h2>Feature Selection</h2>

In [1499]:
n225['Future Close'] = n225['Close'].shift(-1)
n225

High           Low          Open         Close  \
Date                                                                 
2016-01-04  18951.119141  18394.429688  18818.580078  18450.980469   
2016-01-05  18547.380859  18327.519531  18398.759766  18374.000000   
2016-01-06  18469.380859  18064.300781  18410.570312  18191.320312   
2016-01-07  18172.039062  17767.339844  18139.769531  17767.339844   
2016-01-08  17975.310547  17509.640625  17562.230469  17697.960938   
...                  ...           ...           ...           ...   
2021-11-16  29960.929688  29681.250000  29749.710938  29808.119141   
2021-11-17  29909.970703  29623.789062  29906.679688  29688.330078   
2021-11-18  29715.949219  29402.570312  29597.929688  29598.660156   
2021-11-19  29768.539062  29589.189453  29641.050781  29745.869141   
2021-11-22  29806.490234  29542.289062  29618.550781  29774.109375   

                 Volume     Adj Close  Future Close  
Date                                                 
2016-01-04  140200000.0  18450.980469  18374.000000  
2016-01-05  132300000.0  18374.000000  18191.320312  
2016-01-06  142200000.0  18191.320312  17767.339844  
2016-01-07  168000000.0  17767.339844  17697.960938  
2016-01-08  184300000.0  17697.960938  17218.960938  
...                 ...           ...           ...  
2021-11-16   62000000.0  29808.119141  29688.330078  
2021-11-17   63900000.0  29688.330078  29598.660156  
2021-11-18   65400000.0  29598.660156  29745.869141  
2021-11-19   65600000.0  29745.869141  29774.109375  
2021-11-22   58800000.0  29774.109375           NaN  

[1439 rows x 7 columns]

In [1500]:
target = computeTarget(n225['Close'], n225['Future Close'])

n225['Target'] = target
n225_target = n225.tail(1)
n225 = n225.dropna()

In [1501]:
close = n225['Close']
high = n225['High']
low = n225['Low']
open = n225['Open']
volume  = n225['Volume']

In [1502]:
n225_ti = pd.DataFrame()
n225_ti['SMA20'] = talib.SMA(close, timeperiod=20)
n225_ti['SMA50'] = talib.SMA(close, timeperiod=50)
n225_ti['SMA200'] = talib.SMA(close, timeperiod=200)
n225_ti['EMA'] = talib.EMA(close, timeperiod=14)
n225_ti['OBV'] = talib.OBV(close, volume)
n225_ti['RSI14'] = talib.RSI(close, timeperiod=14)
n225_ti['ADX'] = talib.ADX(high, low, close, timeperiod=14)
n225_ti['ADXR'] = talib.ADXR(high, low, close, timeperiod=14)
n225_ti['aroondown'], n225_ti['aroonup'] = talib.AROON(high, low, timeperiod=14)
n225_ti['APO'] = talib.APO(close, fastperiod=12, slowperiod=26, matype=0)
n225_ti['AROONOSC'] = talib.AROONOSC(high, low, timeperiod=14)
n225_ti['BOP'] = talib.BOP(open, high, low, close)
n225_ti['CCI'] = talib.CCI(high, low, close, timeperiod=14)
n225_ti['CMO'] = talib.CMO(close, timeperiod=14)
n225_ti['DX'] = talib.DX(high, low, close, timeperiod=14)
n225_ti['macd'],n225_ti['macdsignal'],n225_ti['macdhist'] = talib.MACD(close, fastperiod = 12, slowperiod=26, signalperiod=9)
n225_ti['MFI'] = talib.MFI(high, low, close, volume, timeperiod=14)
n225_ti['MINUS_DI'] = talib.MINUS_DI(high, low, close, timeperiod=14)
n225_ti['MINUS_DM'] = talib.MINUS_DM(high, low, timeperiod=14)
n225_ti['MOM'] = talib.MOM(close, timeperiod=14)
n225_ti['PLUS_DI'] = talib.PLUS_DI(high, low, close, timeperiod=14)
n225_ti['PLUS_DM'] = talib.PLUS_DM(high, low, timeperiod=14)
n225_ti['PPO'] = talib.PPO(close, fastperiod=12, slowperiod=26, matype=0)
n225_ti['ROC'] = talib.ROC(close, timeperiod=10)
n225_ti['ROCP'] = talib.ROCP(close, timeperiod=10)
n225_ti['ROCR'] = talib.ROCR(close, timeperiod=10)
n225_ti['ROCR100'] = talib.ROCR100(close, timeperiod=10)
n225_ti['slowk'], n225_ti['slowd'] = talib.STOCH(high, low, close, fastk_period=5, slowk_period=3, slowd_period=3, slowd_matype=0)
n225_ti['fastk'], n225_ti['fastd'] = talib.STOCHF(high, low, close, fastk_period=5, fastd_period=3, fastd_matype=0)
n225_ti['TRIX'] = talib.TRIX(close, timeperiod=30)
n225_ti['ULTOSC'] = talib.ULTOSC(high, low, close, timeperiod1=7, timeperiod2=14, timeperiod3=28)
n225_ti['WILLR'] = talib.WILLR(high, low, close, timeperiod=14)
n225_ti['Target'] = n225['Target']
n225_ti

SMA20         SMA50        SMA200           EMA  \
Date                                                                 
2016-01-04           NaN           NaN           NaN           NaN   
2016-01-05           NaN           NaN           NaN           NaN   
2016-01-06           NaN           NaN           NaN           NaN   
2016-01-07           NaN           NaN           NaN           NaN   
2016-01-08           NaN           NaN           NaN           NaN   
...                  ...           ...           ...           ...   
2021-11-15  29233.262109  29297.366875  28901.341738  29352.537538   
2021-11-16  29272.395020  29322.659062  28907.225088  29413.281752   
2021-11-17  29296.035547  29333.863477  28911.555293  29449.954862   
2021-11-18  29313.191016  29332.638867  28916.817695  29469.782235   
2021-11-19  29365.055469  29329.233437  28922.370986  29506.593822   

                     OBV      RSI14        ADX       ADXR  aroondown  \
Date                                                                   
2016-01-04  1.402000e+08        NaN        NaN        NaN        NaN   
2016-01-05  7.900000e+06        NaN        NaN        NaN        NaN   
2016-01-06 -1.343000e+08        NaN        NaN        NaN        NaN   
2016-01-07 -3.023000e+08        NaN        NaN        NaN        NaN   
2016-01-08 -4.866000e+08        NaN        NaN        NaN        NaN   
...                  ...        ...        ...        ...        ...   
2021-11-15  5.710900e+09  58.851897  11.824174  15.413168   0.000000   
2021-11-16  5.772900e+09  59.249153  11.990726  14.860945  21.428571   
2021-11-17  5.709000e+09  56.983099  11.979636  14.369150  14.285714   
2021-11-18  5.643600e+09  55.278742  11.348443  13.825177   7.142857   
2021-11-19  5.709200e+09  57.524806  10.897318  13.343248   0.000000   

               aroonup  ...      ROCR     ROCR100      slowk      slowd  \
Date                    ...                                               
2016-01-04         NaN  ...       NaN         NaN        NaN        NaN   
2016-01-05         NaN  ...       NaN         NaN        NaN        NaN   
2016-01-06         NaN  ...       NaN         NaN        NaN        NaN   
2016-01-07         NaN  ...       NaN         NaN        NaN        NaN   
2016-01-08         NaN  ...       NaN         NaN        NaN        NaN   
...                ...  ...       ...         ...        ...        ...   
2021-11-15   50.000000  ...  1.030600  103.059983  66.522879  39.220148   
2021-11-16  100.000000  ...  1.005432  100.543187  84.425284  62.904204   
2021-11-17   92.857143  ...  1.005672  100.567156  81.149848  77.366004   
2021-11-18   85.714286  ...  0.993431   99.343134  63.762055  76.445729   
2021-11-19   78.571429  ...  1.004535  100.453535  56.454724  67.122209   

                fastk      fastd      TRIX     ULTOSC      WILLR  Target  
Date                                                                      
2016-01-04        NaN        NaN       NaN        NaN        NaN       0  
2016-01-05        NaN        NaN       NaN        NaN        NaN       0  
2016-01-06        NaN        NaN       NaN        NaN        NaN       0  
2016-01-07        NaN        NaN       NaN        NaN        NaN       0  
2016-01-08        NaN        NaN       NaN        NaN        NaN       0  
...               ...        ...       ...        ...        ...     ...  
2021-11-15  89.647116  66.522879  0.034467  49.140580  -7.398881       1  
2021-11-16  83.405483  84.425284  0.035941  49.417832 -10.284253       0  
2021-11-17  70.396946  81.149848  0.037510  49.491904 -18.346138       0  
2021-11-18  37.483737  63.762055  0.039044  56.947511 -24.380985       1  
2021-11-19  61.483490  56.454724  0.040657  60.671533 -23.354579       0  

[1438 rows x 38 columns]

In [1576]:
n225_features = selectFeatures(n225_ti)
n225_features

['RSI14',
 'ADX',
 'ADXR',
 'BOP',
 'CMO',
 'DX',
 'MINUS_DI',
 'PLUS_DI',
 'PPO',
 'ROC',
 'ROCR100',
 'slowk',
 'slowd',
 'fastk',
 'fastd',
 'TRIX',
 'ULTOSC',
 'WILLR']

<h2>จากการทำ Feature Selection ควรจะใช้ 'ADX', 'ADXR', 'BOP', 'CMO', 'MINUS_DI', 'PPO', 'ROC', 'TRIX', 'ULTOSC',
       'WILLR' ในการสร้าง model</h2>

In [1577]:
X = n225_ti.loc[:, n225_features].values
#X = dji_ti.loc[:, ['CCI', 'DX', 'MINUS_DI', 'PLUS_DM', 'slowd']].values
y = n225_ti.loc[:, ['Target']].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [1578]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

<h2>Decision Tree</h2>

In [1579]:
dtc = DecisionTreeClassifier()
dtc.fit(X_train, y_train)

DecisionTreeClassifier()

In [1580]:
# Prediction
#
y_pred = dtc.predict(X_test)  #Accuracy
y_pred

array([0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0,
       0, 1, 0, 1, 1, 0])

In [1581]:
# Look at the actual y_test
#
y_test

array([[0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
    

In [1582]:
# See the accuracy
#
from sklearn import metrics
print('Accuracy Score:', metrics.accuracy_score(y_test, y_pred))

Accuracy Score: 0.5040322580645161


In [1583]:
# See the confusion matrix
#
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[61, 67],
       [56, 64]])

<h2>Random Forest</h2>

<h2>Logistic Regression</h2>

<h2>XGBoost</h2>

<h2>Linear Regress</h2>

<h2>Cauccian Process Regression</h2>

<h1>Heng Seng Index</h1>

<h2>Feature Selection</h2>

In [1514]:
hsi['Future Close'] = hsi['Close'].shift(-1)
hsi

High           Low          Open         Close  \
Date                                                                 
2016-01-04  21794.839844  21227.609375  21782.619141  21327.119141   
2016-01-05  21452.740234  21095.900391  21318.689453  21188.720703   
2016-01-06  21199.619141  20947.300781  21142.630859  20980.810547   
2016-01-07  20826.439453  20323.970703  20772.599609  20333.339844   
2016-01-08  20596.419922  20324.619141  20491.880859  20453.710938   
...                  ...           ...           ...           ...   
2021-11-17  25667.810547  25520.669922  25667.810547  25650.080078   
2021-11-18  25414.210938  25222.599609  25369.880859  25319.720703   
2021-11-19  25077.150391  24825.429688  24934.400391  25049.970703   
2021-11-22  25099.949219  24869.939453  25057.060547  24951.339844   
2021-11-23  24794.720703  24618.740234  24688.990234  24651.580078   

                  Volume     Adj Close  Future Close  
Date                                                  
2016-01-04  1.712095e+09  21327.119141  21188.720703  
2016-01-05  1.484745e+09  21188.720703  20980.810547  
2016-01-06  1.651083e+09  20980.810547  20333.339844  
2016-01-07  2.982004e+09  20333.339844  20453.710938  
2016-01-08  2.078133e+09  20453.710938  19888.500000  
...                  ...           ...           ...  
2021-11-17  1.193809e+09  25650.080078  25319.720703  
2021-11-18  1.342851e+09  25319.720703  25049.970703  
2021-11-19  1.640365e+09  25049.970703  24951.339844  
2021-11-22  1.510359e+09  24951.339844  24651.580078  
2021-11-23  0.000000e+00  24651.580078           NaN  

[1451 rows x 7 columns]

In [1515]:
target = computeTarget(hsi['Close'], hsi['Future Close'])

hsi['Target'] = target
hsi_target = hsi.loc[hsi.index[-1]]
hsi = hsi.dropna()

In [1516]:
close = hsi['Close']
high = hsi['High']
low = hsi['Low']
open = hsi['Open']
volume  = hsi['Volume']

In [1517]:
hsi_ti = pd.DataFrame()
hsi_ti['SMA20'] = talib.SMA(close, timeperiod=20)
hsi_ti['SMA50'] = talib.SMA(close, timeperiod=50)
hsi_ti['SMA200'] = talib.SMA(close, timeperiod=200)
hsi_ti['EMA'] = talib.EMA(close, timeperiod=14)
hsi_ti['OBV'] = talib.OBV(close, volume)
hsi_ti['RSI14'] = talib.RSI(close, timeperiod=14)
hsi_ti['ADX'] = talib.ADX(high, low, close, timeperiod=14)
hsi_ti['ADXR'] = talib.ADXR(high, low, close, timeperiod=14)
hsi_ti['aroondown'], hsi_ti['aroonup'] = talib.AROON(high, low, timeperiod=14)
hsi_ti['APO'] = talib.APO(close, fastperiod=12, slowperiod=26, matype=0)
hsi_ti['AROONOSC'] = talib.AROONOSC(high, low, timeperiod=14)
hsi_ti['BOP'] = talib.BOP(open, high, low, close)
hsi_ti['CCI'] = talib.CCI(high, low, close, timeperiod=14)
hsi_ti['CMO'] = talib.CMO(close, timeperiod=14)
hsi_ti['DX'] = talib.DX(high, low, close, timeperiod=14)
hsi_ti['macd'],hsi_ti['macdsignal'],hsi_ti['macdhist'] = talib.MACD(close, fastperiod = 12, slowperiod=26, signalperiod=9)
hsi_ti['MFI'] = talib.MFI(high, low, close, volume, timeperiod=14)
hsi_ti['MINUS_DI'] = talib.MINUS_DI(high, low, close, timeperiod=14)
hsi_ti['MINUS_DM'] = talib.MINUS_DM(high, low, timeperiod=14)
hsi_ti['MOM'] = talib.MOM(close, timeperiod=14)
hsi_ti['PLUS_DI'] = talib.PLUS_DI(high, low, close, timeperiod=14)
hsi_ti['PLUS_DM'] = talib.PLUS_DM(high, low, timeperiod=14)
hsi_ti['PPO'] = talib.PPO(close, fastperiod=12, slowperiod=26, matype=0)
hsi_ti['ROC'] = talib.ROC(close, timeperiod=10)
hsi_ti['ROCP'] = talib.ROCP(close, timeperiod=10)
hsi_ti['ROCR'] = talib.ROCR(close, timeperiod=10)
hsi_ti['ROCR100'] = talib.ROCR100(close, timeperiod=10)
hsi_ti['slowk'], hsi_ti['slowd'] = talib.STOCH(high, low, close, fastk_period=5, slowk_period=3, slowd_period=3, slowd_matype=0)
hsi_ti['fastk'], hsi_ti['fastd'] = talib.STOCHF(high, low, close, fastk_period=5, fastd_period=3, fastd_matype=0)
hsi_ti['TRIX'] = talib.TRIX(close, timeperiod=30)
hsi_ti['ULTOSC'] = talib.ULTOSC(high, low, close, timeperiod1=7, timeperiod2=14, timeperiod3=28)
hsi_ti['WILLR'] = talib.WILLR(high, low, close, timeperiod=14)
hsi_ti['Target'] = hsi['Target']
hsi_ti

SMA20         SMA50        SMA200           EMA  \
Date                                                                 
2016-01-04           NaN           NaN           NaN           NaN   
2016-01-05           NaN           NaN           NaN           NaN   
2016-01-06           NaN           NaN           NaN           NaN   
2016-01-07           NaN           NaN           NaN           NaN   
2016-01-08           NaN           NaN           NaN           NaN   
...                  ...           ...           ...           ...   
2021-11-16  25432.030957  25215.306484  27506.617119  25277.409626   
2021-11-17  25407.733984  25206.499492  27484.072471  25327.099020   
2021-11-18  25372.843555  25194.854102  27463.714775  25326.115244   
2021-11-19  25318.995605  25172.580898  27442.476982  25289.295972   
2021-11-22  25259.961133  25144.535078  27424.479834  25244.235155   

                     OBV      RSI14        ADX       ADXR  aroondown  \
Date                                                                   
2016-01-04  1.712095e+09        NaN        NaN        NaN        NaN   
2016-01-05  2.273497e+08        NaN        NaN        NaN        NaN   
2016-01-06 -1.423734e+09        NaN        NaN        NaN        NaN   
2016-01-07 -4.405738e+09        NaN        NaN        NaN        NaN   
2016-01-08 -2.327604e+09        NaN        NaN        NaN        NaN   
...                  ...        ...        ...        ...        ...   
2021-11-16  1.907508e+11  58.646649  12.476613  14.799833  71.428571   
2021-11-17  1.895570e+11  57.221959  12.263880  14.301206  64.285714   
2021-11-18  1.882141e+11  50.385653  11.571831  13.974159  57.142857   
2021-11-19  1.865737e+11  45.595592  11.879860  13.655748  50.000000   
2021-11-22  1.850634e+11  43.950340  12.096570  13.569889  42.857143   

              aroonup  ...      ROCR     ROCR100      slowk      slowd  \
Date                   ...                                               
2016-01-04        NaN  ...       NaN         NaN        NaN        NaN   
2016-01-05        NaN  ...       NaN         NaN        NaN        NaN   
2016-01-06        NaN  ...       NaN         NaN        NaN        NaN   
2016-01-07        NaN  ...       NaN         NaN        NaN        NaN   
2016-01-08        NaN  ...       NaN         NaN        NaN        NaN   
...               ...  ...       ...         ...        ...        ...   
2021-11-16   0.000000  ...  1.024467  102.446683  88.443502  84.828571   
2021-11-17  92.857143  ...  1.024988  102.498846  91.253358  88.659208   
2021-11-18  85.714286  ...  1.003747  100.374749  69.048227  82.915029   
2021-11-19  78.571429  ...  1.007216  100.721581  44.706578  68.336054   
2021-11-22  71.428571  ...  1.007574  100.757438  19.466510  44.407105   

                fastk      fastd      TRIX     ULTOSC      WILLR  Target  
Date                                                                      
2016-01-04        NaN        NaN       NaN        NaN        NaN       0  
2016-01-05        NaN        NaN       NaN        NaN        NaN       0  
2016-01-06        NaN        NaN       NaN        NaN        NaN       0  
2016-01-07        NaN        NaN       NaN        NaN        NaN       1  
2016-01-08        NaN        NaN       NaN        NaN        NaN       0  
...               ...        ...       ...        ...        ...     ...  
2021-11-16  97.397636  88.443502 -0.073960  65.696857  -2.602364       0  
2021-11-17  89.387056  91.253358 -0.070285  67.084202  -7.636080       0  
2021-11-18  20.359988  69.048227 -0.066757  62.814885 -33.742134       0  
2021-11-19  24.372689  44.706578 -0.063657  56.756723 -55.058642       0  
2021-11-22  13.666853  19.466510 -0.061031  53.201779 -62.852768       0  

[1450 rows x 38 columns]

In [1592]:
hsi_features = selectFeatures(hsi_ti)
hsi_features

['ADX',
 'ADXR',
 'APO',
 'BOP',
 'CCI',
 'MFI',
 'MINUS_DI',
 'PLUS_DI',
 'PPO',
 'ROC',
 'ROCR100',
 'slowk',
 'slowd',
 'fastk',
 'fastd',
 'TRIX',
 'ULTOSC',
 'WILLR']

In [1594]:
X = hsi_ti.loc[:, hsi_features].values
#X = dji_ti.loc[:, ['CCI', 'DX', 'MINUS_DI', 'PLUS_DM', 'slowd']].values
y = hsi_ti.loc[:, ['Target']].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [1595]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

<h2>Decision Tree</h2>

In [1596]:
dtc = DecisionTreeClassifier()
dtc.fit(X_train, y_train)

DecisionTreeClassifier()

In [1597]:
# Prediction
#
y_pred = dtc.predict(X_test)  #Accuracy
y_pred

array([1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 0])

In [1598]:
# Look at the actual y_test
#
y_test

array([[0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
    

In [1599]:
# See the accuracy
#
from sklearn import metrics
print('Accuracy Score:', metrics.accuracy_score(y_test, y_pred))

Accuracy Score: 0.50199203187251


In [1600]:
# See the confusion matrix
#
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[54, 72],
       [53, 72]])

<h2>Random Forest</h2>

<h2>Logistic Regression</h2>

<h2>XGBoost</h2>

<h2>Linear Regression</h2>

<h2>Gauccian Process Regression</h2>

<h1>SSE Composite Index</h1>

<h2>Feature Selection</h2>

In [1529]:
sse['Future Close'] = sse['Close'].shift(-1)
sse

High          Low         Open        Close      Volume  \
Date                                                                         
2016-01-04  3538.688965  3295.740967  3536.589111  3296.258057      184400   
2016-01-05  3328.138916  3189.604980  3196.650879  3287.710938      266900   
2016-01-06  3362.974121  3288.933105  3291.195068  3361.840088      238900   
2016-01-07  3309.656982  3115.885010  3309.656982  3125.001953       70600   
2016-01-08  3235.450928  3056.877930  3194.625000  3186.412109      286400   
...                 ...          ...          ...          ...         ...   
2021-11-17  3537.510010  3513.520020  3518.560059  3537.370117      276700   
2021-11-18  3537.979980  3513.110107  3531.489990  3520.709961      312400   
2021-11-19  3561.909912  3517.649902  3519.280029  3560.370117      318000   
2021-11-22  3585.187988  3562.750977  3562.762939  3582.080078      330000   
2021-11-23  3598.375000  3577.360840  3580.505859  3589.089355  1641420932   

              Adj Close  Future Close  
Date                                   
2016-01-04  3296.258057   3287.710938  
2016-01-05  3287.710938   3361.840088  
2016-01-06  3361.840088   3125.001953  
2016-01-07  3125.001953   3186.412109  
2016-01-08  3186.412109   3016.704102  
...                 ...           ...  
2021-11-17  3537.370117   3520.709961  
2021-11-18  3520.709961   3560.370117  
2021-11-19  3560.370117   3582.080078  
2021-11-22  3582.080078   3589.089355  
2021-11-23  3589.089355           NaN  

[1431 rows x 7 columns]

In [1530]:
target = computeTarget(sse['Close'], sse['Future Close'])

sse['Target'] = target
sse_target = sse.loc[hsi.index[-1]]
sse = sse.dropna()

In [1531]:
close = sse['Close']
high = sse['High']
low = sse['Low']
open = sse['Open']
volume  = sse['Volume']

In [1532]:
sse_ti = pd.DataFrame()
sse_ti['SMA20'] = talib.SMA(close, timeperiod=20)
sse_ti['SMA50'] = talib.SMA(close, timeperiod=50)
sse_ti['SMA200'] = talib.SMA(close, timeperiod=200)
sse_ti['EMA'] = talib.EMA(close, timeperiod=14)
sse_ti['OBV'] = talib.OBV(close, volume)
sse_ti['RSI14'] = talib.RSI(close, timeperiod=14)
sse_ti['ADX'] = talib.ADX(high, low, close, timeperiod=14)
sse_ti['ADXR'] = talib.ADXR(high, low, close, timeperiod=14)
sse_ti['aroondown'], sse_ti['aroonup'] = talib.AROON(high, low, timeperiod=14)
sse_ti['APO'] = talib.APO(close, fastperiod=12, slowperiod=26, matype=0)
sse_ti['AROONOSC'] = talib.AROONOSC(high, low, timeperiod=14)
sse_ti['BOP'] = talib.BOP(open, high, low, close)
sse_ti['CCI'] = talib.CCI(high, low, close, timeperiod=14)
sse_ti['CMO'] = talib.CMO(close, timeperiod=14)
sse_ti['DX'] = talib.DX(high, low, close, timeperiod=14)
sse_ti['macd'],sse_ti['macdsignal'],sse_ti['macdhist'] = talib.MACD(close, fastperiod = 12, slowperiod=26, signalperiod=9)
sse_ti['MFI'] = talib.MFI(high, low, close, volume, timeperiod=14)
sse_ti['MINUS_DI'] = talib.MINUS_DI(high, low, close, timeperiod=14)
sse_ti['MINUS_DM'] = talib.MINUS_DM(high, low, timeperiod=14)
sse_ti['MOM'] = talib.MOM(close, timeperiod=14)
sse_ti['PLUS_DI'] = talib.PLUS_DI(high, low, close, timeperiod=14)
sse_ti['PLUS_DM'] = talib.PLUS_DM(high, low, timeperiod=14)
sse_ti['PPO'] = talib.PPO(close, fastperiod=12, slowperiod=26, matype=0)
sse_ti['ROC'] = talib.ROC(close, timeperiod=10)
sse_ti['ROCP'] = talib.ROCP(close, timeperiod=10)
sse_ti['ROCR'] = talib.ROCR(close, timeperiod=10)
sse_ti['ROCR100'] = talib.ROCR100(close, timeperiod=10)
sse_ti['slowk'], sse_ti['slowd'] = talib.STOCH(high, low, close, fastk_period=5, slowk_period=3, slowd_period=3, slowd_matype=0)
sse_ti['fastk'], sse_ti['fastd'] = talib.STOCHF(high, low, close, fastk_period=5, fastd_period=3, fastd_matype=0)
sse_ti['TRIX'] = talib.TRIX(close, timeperiod=30)
sse_ti['ULTOSC'] = talib.ULTOSC(high, low, close, timeperiod1=7, timeperiod2=14, timeperiod3=28)
sse_ti['WILLR'] = talib.WILLR(high, low, close, timeperiod=14)
sse_ti['Target'] = sse['Target']
sse_ti

SMA20        SMA50       SMA200          EMA         OBV  \
Date                                                                         
2016-01-04          NaN          NaN          NaN          NaN    184400.0   
2016-01-05          NaN          NaN          NaN          NaN    -82500.0   
2016-01-06          NaN          NaN          NaN          NaN    156400.0   
2016-01-07          NaN          NaN          NaN          NaN     85800.0   
2016-01-08          NaN          NaN          NaN          NaN    372200.0   
...                 ...          ...          ...          ...         ...   
2021-11-16  3539.605518  3579.860229  3527.289161  3528.458933  24156100.0   
2021-11-17  3537.124023  3580.044614  3526.994912  3529.647091  24432800.0   
2021-11-18  3533.420520  3579.580015  3526.766562  3528.455474  24120400.0   
2021-11-19  3532.309021  3579.445415  3526.652953  3532.710760  24438400.0   
2021-11-22  3530.920020  3579.146216  3526.457034  3539.293335  24768400.0   

                RSI14        ADX       ADXR  aroondown     aroonup  ...  \
Date                                                                ...   
2016-01-04        NaN        NaN        NaN        NaN         NaN  ...   
2016-01-05        NaN        NaN        NaN        NaN         NaN  ...   
2016-01-06        NaN        NaN        NaN        NaN         NaN  ...   
2016-01-07        NaN        NaN        NaN        NaN         NaN  ...   
2016-01-08        NaN        NaN        NaN        NaN         NaN  ...   
...               ...        ...        ...        ...         ...  ...   
2021-11-16  45.870457  25.622516  22.424765  71.428571    0.000000  ...   
2021-11-17  49.067261  25.210056  22.776071  64.285714   21.428571  ...   
2021-11-18  45.942678  24.807825  22.922670  57.142857   14.285714  ...   
2021-11-19  53.529165  23.497480  22.955213  50.000000  100.000000  ...   
2021-11-22  57.080036  22.141173  22.915652  42.857143  100.000000  ...   

                ROCR     ROCR100      slowk      slowd      fastk      fastd  \
Date                                                                           
2016-01-04       NaN         NaN        NaN        NaN        NaN        NaN   
2016-01-05       NaN         NaN        NaN        NaN        NaN        NaN   
2016-01-06       NaN         NaN        NaN        NaN        NaN        NaN   
2016-01-07       NaN         NaN        NaN        NaN        NaN        NaN   
2016-01-08       NaN         NaN        NaN        NaN        NaN        NaN   
...              ...         ...        ...        ...        ...        ...   
2021-11-16  1.004610  100.460977  83.443113  86.227132  71.911860  83.443113   
2021-11-17  1.011099  101.109894  78.592268  84.764400  80.668761  78.592268   
2021-11-18  0.998253   99.825336  57.646427  73.227269  20.358659  57.646427   
2021-11-19  1.019705  101.970462  65.957363  67.398686  96.844670  65.957363   
2021-11-22  1.023852  102.385225  70.963817  64.855869  95.688122  70.963817   

                TRIX     ULTOSC      WILLR  Target  
Date                                                
2016-01-04       NaN        NaN        NaN       0  
2016-01-05       NaN        NaN        NaN       1  
2016-01-06       NaN        NaN        NaN       0  
2016-01-07       NaN        NaN        NaN       1  
2016-01-08       NaN        NaN        NaN       0  
...              ...        ...        ...     ...  
2021-11-16 -0.000020  61.270883 -33.685900       1  
2021-11-17 -0.002265  65.254481 -19.600317       0  
2021-11-18 -0.004395  61.566902 -34.662373       1  
2021-11-19 -0.006107  64.791843  -1.357007       1  
2021-11-22 -0.007290  63.482566  -2.272727       1  

[1430 rows x 38 columns]

In [1601]:
sse_features = selectFeatures(sse_ti)
sse_features

['SMA20',
 'EMA',
 'APO',
 'BOP',
 'CCI',
 'CMO',
 'DX',
 'macd',
 'macdhist',
 'MFI',
 'PPO',
 'ROC',
 'ROCR100',
 'slowk',
 'slowd',
 'fastd',
 'TRIX',
 'ULTOSC']

In [1603]:
X = sse_ti.loc[:, sse_features].values
#X = dji_ti.loc[:, ['CCI', 'DX', 'MINUS_DI', 'PLUS_DM', 'slowd']].values
y = sse_ti.loc[:, ['Target']].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [1604]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

<h2>Decision Tree</h2>

In [1605]:
dtc = DecisionTreeClassifier()
dtc.fit(X_train, y_train)

DecisionTreeClassifier()

In [1606]:
# Prediction
#
y_pred = dtc.predict(X_test)  #Accuracy
y_pred

array([0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 1, 1, 1, 0])

In [1607]:
# Look at the actual y_test
#
y_test

array([[1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
    

In [1608]:
# See the accuracy
#
from sklearn import metrics
print('Accuracy Score:', metrics.accuracy_score(y_test, y_pred))

Accuracy Score: 0.5668016194331984


In [1609]:
# See the confusion matrix
#
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[83, 44],
       [63, 57]])

<h2>Random Forest</h2>

<h2>Logistic Regression</h2>

<h2>XGBoost</h2>

<h2>Linear Regression</h2>

<h2>Gauccian Process Regression</h2>