In [898]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import pandas_datareader as pdr
import seaborn as sns
import talib 
from sklearn.preprocessing import MinMaxScaler
from sklearn import tree
from sklearn.linear_model import LinearRegression
from sklearn.feature_selection import RFE
from mlxtend.feature_selection import SequentialFeatureSelector as SFS



In [900]:
startdate = '2016-01-1'
enddate= '2021-12-31'
scaler = MinMaxScaler()

In [902]:
dji = pdr.get_data_yahoo('^DJI', start=startdate, end=enddate)
dji_norm = pd.DataFrame(scaler.fit_transform(dji), columns=dji.columns)
n225 = pdr.get_data_yahoo("^N225", start=startdate, end=enddate)
n225_norm = pd.DataFrame(scaler.fit_transform(n225), columns=n225.columns)
hsi = pdr.get_data_yahoo("^HSI", start=startdate, end=enddate)
hsi_norm = pd.DataFrame(scaler.fit_transform(hsi), columns=hsi.columns)
sse = pdr.get_data_yahoo("000001.SS", start=startdate, end=enddate)
sse_norm = pd.DataFrame(scaler.fit_transform(sse), columns=sse.columns)


<h1>Dow Jones Industrial Average</h1>

<h2>Feature Selection</h2>

In [ ]:
dji['Future Close'] = dji['Close'].shift(-1)
dji

In [901]:
def computeTarget(present_price, future_price):
    score = (( future_price - present_price ) / present_price ) * 100
    target = []
    for i in score:
        if i > 0:
            target.append(1)
        else:
            target.append(0)
    return target
# 2 = up, 1 = down, 0 = sideway

In [952]:

target = computeTarget(dji['Close'], dji['Future Close'])

dji['Target'] = target


/var/folders/_t/ffqnjnx55t7_d2v9hx5smxm00000gn/T/ipykernel_44804/25613601.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dji['Target'] = target


In [905]:
dji_target = dji.tail(1)
dji_target
dji = dji.dropna()

In [906]:
close = dji['Close']
high = dji['High']
low = dji['Low']
open = dji['Open']
volume  = dji['Volume']

In [907]:
dji_ti = pd.DataFrame()
dji_ti['SMA20'] = talib.SMA(close, timeperiod=20)
dji_ti['SMA50'] = talib.SMA(close, timeperiod=50)
dji_ti['SMA200'] = talib.SMA(close, timeperiod=200)
dji_ti['EMA'] = talib.EMA(close, timeperiod=14)
dji_ti['OBV'] = talib.OBV(close, volume)
dji_ti['RSI14'] = talib.RSI(close, timeperiod=14)
dji_ti['ADX'] = talib.ADX(high, low, close, timeperiod=14)
dji_ti['ADXR'] = talib.ADXR(high, low, close, timeperiod=14)
dji_ti['aroondown'], dji_ti['aroonup'] = talib.AROON(high, low, timeperiod=14)
dji_ti['APO'] = talib.APO(close, fastperiod=12, slowperiod=26, matype=0)
dji_ti['AROONOSC'] = talib.AROONOSC(high, low, timeperiod=14)
dji_ti['BOP'] = talib.BOP(open, high, low, close)
dji_ti['CCI'] = talib.CCI(high, low, close, timeperiod=14)
dji_ti['CMO'] = talib.CMO(close, timeperiod=14)
dji_ti['DX'] = talib.DX(high, low, close, timeperiod=14)
dji_ti['macd'],dji_ti['macdsignal'],dji_ti['macdhist'] = talib.MACD(close, fastperiod = 12, slowperiod=26, signalperiod=9)
dji_ti['MFI'] = talib.MFI(high, low, close, volume, timeperiod=14)
dji_ti['MINUS_DI'] = talib.MINUS_DI(high, low, close, timeperiod=14)
dji_ti['MINUS_DM'] = talib.MINUS_DM(high, low, timeperiod=14)
dji_ti['MOM'] = talib.MOM(close, timeperiod=14)
dji_ti['PLUS_DI'] = talib.PLUS_DI(high, low, close, timeperiod=14)
dji_ti['PLUS_DM'] = talib.PLUS_DM(high, low, timeperiod=14)
dji_ti['PPO'] = talib.PPO(close, fastperiod=12, slowperiod=26, matype=0)
dji_ti['ROC'] = talib.ROC(close, timeperiod=10)
dji_ti['ROCP'] = talib.ROCP(close, timeperiod=10)
dji_ti['ROCR'] = talib.ROCR(close, timeperiod=10)
dji_ti['ROCR100'] = talib.ROCR100(close, timeperiod=10)
dji_ti['slowk'], dji_ti['slowd'] = talib.STOCH(high, low, close, fastk_period=5, slowk_period=3, slowd_period=3, slowd_matype=0)
dji_ti['fastk'], dji_ti['fastd'] = talib.STOCHF(high, low, close, fastk_period=5, fastd_period=3, fastd_matype=0)
dji_ti['TRIX'] = talib.TRIX(close, timeperiod=30)
dji_ti['ULTOSC'] = talib.ULTOSC(high, low, close, timeperiod1=7, timeperiod2=14, timeperiod3=28)
dji_ti['WILLR'] = talib.WILLR(high, low, close, timeperiod=14)
dji_ti['Target'] = dji['Target']
dji_ti

KeyError: 'Target'

In [872]:
# plt.figure(figsize=(12,10))
# cor = ti.corr()
# sns.heatmap(cor, annot=True, cmap=plt.cm.Reds)
# plt.show()

In [873]:
# cor_target = abs(cor["Target"])
# features = cor_target[cor_target>0.05]
# features

In [874]:
dji_ti = dji_ti.dropna()
X = dji_ti.drop("Target", axis=1)  # Feature Matrix
y = dji_ti["Target"]               # Target Variable
y

Date
2016-10-14    0
2016-10-17    1
2016-10-18    1
2016-10-19    0
2016-10-20    0
             ..
2021-11-15    1
2021-11-16    0
2021-11-17    0
2021-11-18    0
2021-11-19    1
Name: Target, Length: 1285, dtype: int64

In [875]:
X = X.fillna(0)

In [876]:
#X.isna().sum()

In [877]:
model = LinearRegression()

#Initializing RFE model
rfe = RFE(model, n_features_to_select=7)

#Transforming data using RFE
X_rfe = rfe.fit_transform(X,y)  

#Fitting the data to model
model.fit(X_rfe,y)

print(rfe.support_)
print(rfe.ranking_)

[False False False False False  True False False False False False False
  True False  True False False False False False False False False  True
 False False  True False False  True False False False False  True False
 False]
[19 18 30 28 31  1  9  8  7 17 15 16  1 12  1 20 14 13 23 27  3 24 29  1
 22  4  1 25 26  1  6 10 21 11  1  2  5]


In [878]:
# no. of features
#
nof_list = np.arange(1, 13)            
high_score = 0

# Variable to store the optimum features
#
nof = 0           
score_list = []

for n in range(len(nof_list)):
    X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.9, random_state = 0)

    model = LinearRegression()
    rfe = RFE(model, n_features_to_select=nof_list[n])
    X_train_rfe = rfe.fit_transform(X_train,y_train)
    X_test_rfe = rfe.transform(X_test)
    model.fit(X_train_rfe,y_train)

    score = model.score(X_test_rfe,y_test)
    score_list.append(score)

    if(score > high_score):
        high_score = score
        nof = nof_list[n]

print("Optimum number of features: %d" % nof)
print("Score with %d features: %f" % (nof, high_score))

Optimum number of features: 0
Score with 0 features: 0.000000


In [879]:
cols = list(X.columns)
model = LinearRegression()

# Initializing RFE model
rfe = RFE(model, n_features_to_select=10)             

# Transforming data using RFE
X_rfe = rfe.fit_transform(X,y)  

# Fitting the data to model
model.fit(X_rfe,y)              
temp = pd.Series(rfe.support_, index = cols)
selected_features_rfe = temp[temp==True].index

print(selected_features_rfe)

Index(['RSI14', 'BOP', 'CMO', 'MINUS_DI', 'PLUS_DI', 'PPO', 'ROC', 'ROCR100',
       'TRIX', 'ULTOSC'],
      dtype='object')


In [817]:
# dji_ti = dji_ti.dropna()
# X = dji_ti.drop("Target", axis=1)  # Feature Matrix
# y = dji_ti["Target"]               # Target Variable
# #Split the features and target data
# #Define Sequential Forward Selection (sfs)
# sfs = SFS(LinearRegression(),
#            k_features=5,
#            forward=True,
#            floating=False,
#            scoring = 'r2',
#            cv = 0)
# #Use SFS to select the top 5 features 
# sfs.fit(X, y)

# #Create a dataframe for the SFS results 
# df_SFS_results = pd.DataFrame(sfs.subsets_).transpose()
# df_SFS_results


<h2>จากการทำ Feature Selection ควรจะใช้ 'RSI14', 'BOP', 'CMO', 'MINUS_DI', 'PLUS_DI', 'PPO', 'ROC', 'ROCR100','TRIX', 'ULTOSC' ในการสร้าง model</h2>

In [818]:
from sklearn.model_selection import train_test_split
X = dji_ti.loc[:, ['RSI14', 'BOP', 'CMO', 'MINUS_DI', 'PLUS_DI', 'PPO', 'ROC', 'ROCR100','TRIX', 'ULTOSC']].values
#X = dji_ti.loc[:, ['CCI', 'DX', 'MINUS_DI', 'PLUS_DM', 'slowd']].values
y = dji_ti.loc[:, ['Target']].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [819]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [820]:
# Visualize the data
#
def visualize(title, xlabel, ylabel, classifier, X_test, y_test):
    X_set, y_set = X_test, y_test
    X1, X2 = np.meshgrid(np.arange(start = X_set[:, 0].min() - 1, stop = X_set[:, 0].max() + 1, step = 0.01),
                         np.arange(start = X_set[:, 1].min() - 1, stop = X_set[:, 1].max() + 1, step = 0.01))
    plt.contourf(X1, X2, classifier.predict(np.array([X1.ravel(), X2.ravel()]).T).reshape(X1.shape),
                 alpha = 0.75, cmap = ListedColormap(('lightblue', 'cornsilk')))
    plt.xlim(X1.min(), X1.max())
    plt.ylim(X2.min(), X2.max())

    for i, j in enumerate(np.unique(y_set)):
        plt.scatter(X_set[y_set == j, 0], X_set[y_set == j, 1], label = j)

    plt.title(title)
    plt.xlabel(xlabel)
    plt.ylabel(ylabel)
    plt.legend()
    plt.show()

<h2>Decision Tree</h2>

In [821]:
# Decision Tree Classifier: Create and Train the model
#
from sklearn.tree import DecisionTreeClassifier

dtc = DecisionTreeClassifier()
dtc.fit(X_train, y_train)

DecisionTreeClassifier()

In [822]:
# Prediction
#
y_pred = dtc.predict(X_test)  #Accuracy
y_pred

array([1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1])

In [823]:
# Look at the actual y_test
#
y_test

array([[0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
    

In [824]:
# See the accuracy
#
from sklearn import metrics
print('Accuracy Score:', metrics.accuracy_score(y_test, y_pred))

Accuracy Score: 0.5271317829457365


In [825]:
# See the confusion matrix
#
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[50, 62],
       [60, 86]])

<h2>Random Forest</h2>

<h2>Logistic Regression</h2>

<h2>XGBoost</h2>

<h2>Linear Regression</h2>

<h2>Gauccian Process Regress</h2>

<h1>Nikkei 225 Stock Average</h1>

<h2>Feature Selection</h2>

In [880]:
n225['Future Close'] = n225['Close'].shift(-1)
n225

/var/folders/_t/ffqnjnx55t7_d2v9hx5smxm00000gn/T/ipykernel_44804/2336074776.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  n225['Future Close'] = n225['Close'].shift(-1)


High           Low          Open         Close  \
Date                                                                 
2016-01-04  18951.119141  18394.429688  18818.580078  18450.980469   
2016-01-05  18547.380859  18327.519531  18398.759766  18374.000000   
2016-01-06  18469.380859  18064.300781  18410.570312  18191.320312   
2016-01-07  18172.039062  17767.339844  18139.769531  17767.339844   
2016-01-08  17975.310547  17509.640625  17562.230469  17697.960938   
...                  ...           ...           ...           ...   
2021-11-15  29861.880859  29718.210938  29807.369141  29776.800781   
2021-11-16  29960.929688  29681.250000  29749.710938  29808.119141   
2021-11-17  29909.970703  29623.789062  29906.679688  29688.330078   
2021-11-18  29715.949219  29402.570312  29597.929688  29598.660156   
2021-11-19  29768.539062  29589.189453  29641.050781  29745.869141   

                 Volume     Adj Close  Future Close  Target  
Date                                                         
2016-01-04  140200000.0  18450.980469  18374.000000       0  
2016-01-05  132300000.0  18374.000000  18191.320312       0  
2016-01-06  142200000.0  18191.320312  17767.339844       0  
2016-01-07  168000000.0  17767.339844  17697.960938       0  
2016-01-08  184300000.0  17697.960938  17218.960938       0  
...                 ...           ...           ...     ...  
2021-11-15   60400000.0  29776.800781  29808.119141       1  
2021-11-16   62000000.0  29808.119141  29688.330078       0  
2021-11-17   63900000.0  29688.330078  29598.660156       0  
2021-11-18   65400000.0  29598.660156  29745.869141       1  
2021-11-19   65600000.0  29745.869141           NaN       1  

[1438 rows x 8 columns]

In [881]:
target = computeTarget(n225['Close'], n225['Future Close'])

n225['Target'] = target
n225_target = n225.tail(1)
n225 = n225.dropna()

/var/folders/_t/ffqnjnx55t7_d2v9hx5smxm00000gn/T/ipykernel_44804/318589239.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  n225['Target'] = target


In [882]:
close = n225['Close']
high = n225['High']
low = n225['Low']
open = n225['Open']
volume  = n225['Volume']

In [883]:
n225_ti = pd.DataFrame()
n225_ti['SMA20'] = talib.SMA(close, timeperiod=20)
n225_ti['SMA50'] = talib.SMA(close, timeperiod=50)
n225_ti['SMA200'] = talib.SMA(close, timeperiod=200)
n225_ti['EMA'] = talib.EMA(close, timeperiod=14)
n225_ti['OBV'] = talib.OBV(close, volume)
n225_ti['RSI14'] = talib.RSI(close, timeperiod=14)
n225_ti['ADX'] = talib.ADX(high, low, close, timeperiod=14)
n225_ti['ADXR'] = talib.ADXR(high, low, close, timeperiod=14)
n225_ti['aroondown'], n225_ti['aroonup'] = talib.AROON(high, low, timeperiod=14)
n225_ti['APO'] = talib.APO(close, fastperiod=12, slowperiod=26, matype=0)
n225_ti['AROONOSC'] = talib.AROONOSC(high, low, timeperiod=14)
n225_ti['BOP'] = talib.BOP(open, high, low, close)
n225_ti['CCI'] = talib.CCI(high, low, close, timeperiod=14)
n225_ti['CMO'] = talib.CMO(close, timeperiod=14)
n225_ti['DX'] = talib.DX(high, low, close, timeperiod=14)
n225_ti['macd'],n225_ti['macdsignal'],n225_ti['macdhist'] = talib.MACD(close, fastperiod = 12, slowperiod=26, signalperiod=9)
n225_ti['MFI'] = talib.MFI(high, low, close, volume, timeperiod=14)
n225_ti['MINUS_DI'] = talib.MINUS_DI(high, low, close, timeperiod=14)
n225_ti['MINUS_DM'] = talib.MINUS_DM(high, low, timeperiod=14)
n225_ti['MOM'] = talib.MOM(close, timeperiod=14)
n225_ti['PLUS_DI'] = talib.PLUS_DI(high, low, close, timeperiod=14)
n225_ti['PLUS_DM'] = talib.PLUS_DM(high, low, timeperiod=14)
n225_ti['PPO'] = talib.PPO(close, fastperiod=12, slowperiod=26, matype=0)
n225_ti['ROC'] = talib.ROC(close, timeperiod=10)
n225_ti['ROCP'] = talib.ROCP(close, timeperiod=10)
n225_ti['ROCR'] = talib.ROCR(close, timeperiod=10)
n225_ti['ROCR100'] = talib.ROCR100(close, timeperiod=10)
n225_ti['slowk'], n225_ti['slowd'] = talib.STOCH(high, low, close, fastk_period=5, slowk_period=3, slowd_period=3, slowd_matype=0)
n225_ti['fastk'], n225_ti['fastd'] = talib.STOCHF(high, low, close, fastk_period=5, fastd_period=3, fastd_matype=0)
n225_ti['TRIX'] = talib.TRIX(close, timeperiod=30)
n225_ti['ULTOSC'] = talib.ULTOSC(high, low, close, timeperiod1=7, timeperiod2=14, timeperiod3=28)
n225_ti['WILLR'] = talib.WILLR(high, low, close, timeperiod=14)
n225_ti['Target'] = n225['Target']
n225_ti

SMA20         SMA50        SMA200           EMA  \
Date                                                                 
2016-01-04           NaN           NaN           NaN           NaN   
2016-01-05           NaN           NaN           NaN           NaN   
2016-01-06           NaN           NaN           NaN           NaN   
2016-01-07           NaN           NaN           NaN           NaN   
2016-01-08           NaN           NaN           NaN           NaN   
...                  ...           ...           ...           ...   
2021-11-12  29197.853613  29270.851250  28896.242031  29287.266270   
2021-11-15  29233.262109  29297.366875  28901.341738  29352.537538   
2021-11-16  29272.395020  29322.659062  28907.225088  29413.281752   
2021-11-17  29296.035547  29333.863477  28911.555293  29449.954862   
2021-11-18  29313.191016  29332.638867  28916.817695  29469.782235   

                     OBV      RSI14        ADX       ADXR  aroondown  \
Date                                                                   
2016-01-04  1.402000e+08        NaN        NaN        NaN        NaN   
2016-01-05  7.900000e+06        NaN        NaN        NaN        NaN   
2016-01-06 -1.343000e+08        NaN        NaN        NaN        NaN   
2016-01-07 -3.023000e+08        NaN        NaN        NaN        NaN   
2016-01-08 -4.866000e+08        NaN        NaN        NaN        NaN   
...                  ...        ...        ...        ...        ...   
2021-11-12  5.650500e+09  56.767222  11.871649  16.094257   7.142857   
2021-11-15  5.710900e+09  58.851897  11.824174  15.413168   0.000000   
2021-11-16  5.772900e+09  59.249153  11.990726  14.860945  21.428571   
2021-11-17  5.709000e+09  56.983099  11.979636  14.369150  14.285714   
2021-11-18  5.643600e+09  55.278742  11.348443  13.825177   7.142857   

               aroonup  ...      ROCR     ROCR100      slowk      slowd  \
Date                    ...                                               
2016-01-04         NaN  ...       NaN         NaN        NaN        NaN   
2016-01-05         NaN  ...       NaN         NaN        NaN        NaN   
2016-01-06         NaN  ...       NaN         NaN        NaN        NaN   
2016-01-07         NaN  ...       NaN         NaN        NaN        NaN   
2016-01-08         NaN  ...       NaN         NaN        NaN        NaN   
...                ...  ...       ...         ...        ...        ...   
2021-11-12   57.142857  ...  1.027407  102.740730  37.764451  22.542156   
2021-11-15   50.000000  ...  1.030600  103.059983  66.522879  39.220148   
2021-11-16  100.000000  ...  1.005432  100.543187  84.425284  62.904204   
2021-11-17   92.857143  ...  1.005672  100.567156  81.149848  77.366004   
2021-11-18   85.714286  ...  0.993431   99.343134  63.762055  76.445729   

                fastk      fastd      TRIX     ULTOSC      WILLR  Target  
Date                                                                      
2016-01-04        NaN        NaN       NaN        NaN        NaN       0  
2016-01-05        NaN        NaN       NaN        NaN        NaN       0  
2016-01-06        NaN        NaN       NaN        NaN        NaN       0  
2016-01-07        NaN        NaN       NaN        NaN        NaN       0  
2016-01-08        NaN        NaN       NaN        NaN        NaN       0  
...               ...        ...       ...        ...        ...     ...  
2021-11-12  80.223252  37.764451  0.033280  49.952988 -19.232236       1  
2021-11-15  89.647116  66.522879  0.034467  49.140580  -7.398881       1  
2021-11-16  83.405483  84.425284  0.035941  49.417832 -10.284253       0  
2021-11-17  70.396946  81.149848  0.037510  49.491904 -18.346138       0  
2021-11-18  37.483737  63.762055  0.039044  56.947511 -24.380985       1  

[1437 rows x 38 columns]

In [884]:
n225_ti = n225_ti.dropna()
X = n225_ti.drop("Target", axis=1)  # Feature Matrix
y = n225_ti["Target"]               # Target Variable

In [885]:
model = LinearRegression()

#Initializing RFE model
rfe = RFE(model, n_features_to_select=7)

#Transforming data using RFE
X_rfe = rfe.fit_transform(X,y)  

#Fitting the data to model
model.fit(X_rfe,y)

print(rfe.support_)
print(rfe.ranking_)

[False False False False False False False  True False False False False
  True False  True False False False False False  True False False False
 False False False False False  True False False False False  True  True
 False]
[17 26 30 18 31 11  2  1 13 22 14 27  1 19  1 12 20 21 16 15  1 24 23  5
 25  3  6 29 28  1 10  7  9  8  1  1  4]


In [886]:
# no. of features
#
nof_list = np.arange(1, 13)            
high_score = 0

# Variable to store the optimum features
#
nof = 0           
score_list = []

for n in range(len(nof_list)):
    X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.9, random_state = 0)

    model = LinearRegression()
    rfe = RFE(model, n_features_to_select=nof_list[n])
    X_train_rfe = rfe.fit_transform(X_train,y_train)
    X_test_rfe = rfe.transform(X_test)
    model.fit(X_train_rfe,y_train)

    score = model.score(X_test_rfe,y_test)
    score_list.append(score)

    if(score > high_score):
        high_score = score
        nof = nof_list[n]

print("Optimum number of features: %d" % nof)
print("Score with %d features: %f" % (nof, high_score))

Optimum number of features: 0
Score with 0 features: 0.000000


In [887]:
cols = list(X.columns)
model = LinearRegression()

# Initializing RFE model
rfe = RFE(model, n_features_to_select=10)             

# Transforming data using RFE
X_rfe = rfe.fit_transform(X,y)  

# Fitting the data to model
model.fit(X_rfe,y)              
temp = pd.Series(rfe.support_, index = cols)
selected_features_rfe = temp[temp==True].index

print(selected_features_rfe)

Index(['ADX', 'ADXR', 'BOP', 'CMO', 'MINUS_DI', 'PPO', 'ROCR100', 'TRIX',
       'ULTOSC', 'WILLR'],
      dtype='object')


<h2>จากการทำ Feature Selection ควรจะใช้ 'ADX', 'ADXR', 'BOP', 'CMO', 'MINUS_DI', 'PPO', 'ROC', 'TRIX', 'ULTOSC',
       'WILLR' ในการสร้าง model</h2>

In [912]:
X = n225_ti.loc[:, ['ADX', 'ADXR', 'BOP', 'CMO', 'MINUS_DI', 'PPO', 'ROCR100', 'TRIX', 'ULTOSC', 'WILLR']].values
#X = dji_ti.loc[:, ['CCI', 'DX', 'MINUS_DI', 'PLUS_DM', 'slowd']].values
y = n225_ti.loc[:, ['Target']].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [913]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

<h2>Decision Tree</h2>

In [914]:
dtc = DecisionTreeClassifier()
dtc.fit(X_train, y_train)

DecisionTreeClassifier()

In [915]:
# Prediction
#
y_pred = dtc.predict(X_test)  #Accuracy
y_pred

array([0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 1, 1, 1])

In [916]:
# Look at the actual y_test
#
y_test

array([[0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
    

In [917]:
# See the accuracy
#
from sklearn import metrics
print('Accuracy Score:', metrics.accuracy_score(y_test, y_pred))

Accuracy Score: 0.4838709677419355


In [918]:
# See the confusion matrix
#
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[53, 59],
       [69, 67]])

<h2>Random Forest</h2>

<h2>Logistic Regression</h2>

<h2>XGBoost</h2>

<h2>Linear Regress</h2>

<h2>Cauccian Process Regression</h2>

<h1>Heng Seng Index</h1>

<h2>Feature Selection</h2>

In [888]:
hsi['Future Close'] = hsi['Close'].shift(-1)
hsi

High           Low          Open         Close  \
Date                                                                 
2016-01-04  21794.839844  21227.609375  21782.619141  21327.119141   
2016-01-05  21452.740234  21095.900391  21318.689453  21188.720703   
2016-01-06  21199.619141  20947.300781  21142.630859  20980.810547   
2016-01-07  20826.439453  20323.970703  20772.599609  20333.339844   
2016-01-08  20596.419922  20324.619141  20491.880859  20453.710938   
...                  ...           ...           ...           ...   
2021-11-16  25746.710938  25410.869141  25446.650391  25713.779297   
2021-11-17  25667.810547  25520.669922  25667.810547  25650.080078   
2021-11-18  25414.210938  25222.599609  25369.880859  25319.720703   
2021-11-19  25077.150391  24825.429688  24934.400391  25049.970703   
2021-11-22  25099.949219  24869.939453  25057.060547  24951.339844   

                  Volume     Adj Close  Future Close  Target  
Date                                                          
2016-01-04  1.712095e+09  21327.119141  21188.720703       0  
2016-01-05  1.484745e+09  21188.720703  20980.810547       0  
2016-01-06  1.651083e+09  20980.810547  20333.339844       0  
2016-01-07  2.982004e+09  20333.339844  20453.710938       1  
2016-01-08  2.078133e+09  20453.710938  19888.500000       0  
...                  ...           ...           ...     ...  
2021-11-16  1.528784e+09  25713.779297  25650.080078       0  
2021-11-17  1.193809e+09  25650.080078  25319.720703       0  
2021-11-18  1.342851e+09  25319.720703  25049.970703       0  
2021-11-19  1.640365e+09  25049.970703  24951.339844       0  
2021-11-22  1.510359e+09  24951.339844           NaN       0  

[1450 rows x 8 columns]

In [889]:
target = computeTarget(hsi['Close'], hsi['Future Close'])

hsi['Target'] = target
hsi_target = hsi.loc[hsi.index[-1]]
hsi = hsi.dropna()

In [890]:
close = hsi['Close']
high = hsi['High']
low = hsi['Low']
open = hsi['Open']
volume  = hsi['Volume']

In [891]:
hsi_ti = pd.DataFrame()
hsi_ti['SMA20'] = talib.SMA(close, timeperiod=20)
hsi_ti['SMA50'] = talib.SMA(close, timeperiod=50)
hsi_ti['SMA200'] = talib.SMA(close, timeperiod=200)
hsi_ti['EMA'] = talib.EMA(close, timeperiod=14)
hsi_ti['OBV'] = talib.OBV(close, volume)
hsi_ti['RSI14'] = talib.RSI(close, timeperiod=14)
hsi_ti['ADX'] = talib.ADX(high, low, close, timeperiod=14)
hsi_ti['ADXR'] = talib.ADXR(high, low, close, timeperiod=14)
hsi_ti['aroondown'], hsi_ti['aroonup'] = talib.AROON(high, low, timeperiod=14)
hsi_ti['APO'] = talib.APO(close, fastperiod=12, slowperiod=26, matype=0)
hsi_ti['AROONOSC'] = talib.AROONOSC(high, low, timeperiod=14)
hsi_ti['BOP'] = talib.BOP(open, high, low, close)
hsi_ti['CCI'] = talib.CCI(high, low, close, timeperiod=14)
hsi_ti['CMO'] = talib.CMO(close, timeperiod=14)
hsi_ti['DX'] = talib.DX(high, low, close, timeperiod=14)
hsi_ti['macd'],hsi_ti['macdsignal'],hsi_ti['macdhist'] = talib.MACD(close, fastperiod = 12, slowperiod=26, signalperiod=9)
hsi_ti['MFI'] = talib.MFI(high, low, close, volume, timeperiod=14)
hsi_ti['MINUS_DI'] = talib.MINUS_DI(high, low, close, timeperiod=14)
hsi_ti['MINUS_DM'] = talib.MINUS_DM(high, low, timeperiod=14)
hsi_ti['MOM'] = talib.MOM(close, timeperiod=14)
hsi_ti['PLUS_DI'] = talib.PLUS_DI(high, low, close, timeperiod=14)
hsi_ti['PLUS_DM'] = talib.PLUS_DM(high, low, timeperiod=14)
hsi_ti['PPO'] = talib.PPO(close, fastperiod=12, slowperiod=26, matype=0)
hsi_ti['ROC'] = talib.ROC(close, timeperiod=10)
hsi_ti['ROCP'] = talib.ROCP(close, timeperiod=10)
hsi_ti['ROCR'] = talib.ROCR(close, timeperiod=10)
hsi_ti['ROCR100'] = talib.ROCR100(close, timeperiod=10)
hsi_ti['slowk'], hsi_ti['slowd'] = talib.STOCH(high, low, close, fastk_period=5, slowk_period=3, slowd_period=3, slowd_matype=0)
hsi_ti['fastk'], hsi_ti['fastd'] = talib.STOCHF(high, low, close, fastk_period=5, fastd_period=3, fastd_matype=0)
hsi_ti['TRIX'] = talib.TRIX(close, timeperiod=30)
hsi_ti['ULTOSC'] = talib.ULTOSC(high, low, close, timeperiod1=7, timeperiod2=14, timeperiod3=28)
hsi_ti['WILLR'] = talib.WILLR(high, low, close, timeperiod=14)
hsi_ti['Target'] = hsi['Target']
hsi_ti

SMA20         SMA50        SMA200           EMA  \
Date                                                                 
2016-01-04           NaN           NaN           NaN           NaN   
2016-01-05           NaN           NaN           NaN           NaN   
2016-01-06           NaN           NaN           NaN           NaN   
2016-01-07           NaN           NaN           NaN           NaN   
2016-01-08           NaN           NaN           NaN           NaN   
...                  ...           ...           ...           ...   
2021-11-15  25435.702539  25221.596680  27525.287471  25210.275831   
2021-11-16  25432.030957  25215.306484  27506.617119  25277.409626   
2021-11-17  25407.733984  25206.499492  27484.072471  25327.099020   
2021-11-18  25372.843555  25194.854102  27463.714775  25326.115244   
2021-11-19  25318.995605  25172.580898  27442.476982  25289.295972   

                     OBV      RSI14        ADX       ADXR  aroondown  \
Date                                                                   
2016-01-04  1.712095e+09        NaN        NaN        NaN        NaN   
2016-01-05  2.273497e+08        NaN        NaN        NaN        NaN   
2016-01-06 -1.423734e+09        NaN        NaN        NaN        NaN   
2016-01-07 -4.405738e+09        NaN        NaN        NaN        NaN   
2016-01-08 -2.327604e+09        NaN        NaN        NaN        NaN   
...                  ...        ...        ...        ...        ...   
2021-11-15  1.892220e+11  53.157491  12.705711  15.549905  78.571429   
2021-11-16  1.907508e+11  58.646649  12.476613  14.799833  71.428571   
2021-11-17  1.895570e+11  57.221959  12.263880  14.301206  64.285714   
2021-11-18  1.882141e+11  50.385653  11.571831  13.974159  57.142857   
2021-11-19  1.865737e+11  45.595592  11.879860  13.655748  50.000000   

              aroonup  ...      ROCR     ROCR100      slowk      slowd  \
Date                   ...                                               
2016-01-04        NaN  ...       NaN         NaN        NaN        NaN   
2016-01-05        NaN  ...       NaN         NaN        NaN        NaN   
2016-01-06        NaN  ...       NaN         NaN        NaN        NaN   
2016-01-07        NaN  ...       NaN         NaN        NaN        NaN   
2016-01-08        NaN  ...       NaN         NaN        NaN        NaN   
...               ...  ...       ...         ...        ...        ...   
2021-11-15   0.000000  ...  1.009406  100.940554  86.280765  76.202418   
2021-11-16   0.000000  ...  1.024467  102.446683  88.443502  84.828571   
2021-11-17  92.857143  ...  1.024988  102.498846  91.253358  88.659208   
2021-11-18  85.714286  ...  1.003747  100.374749  69.048227  82.915029   
2021-11-19  78.571429  ...  1.007216  100.721581  44.706578  68.336054   

                fastk      fastd      TRIX     ULTOSC      WILLR  Target  
Date                                                                      
2016-01-04        NaN        NaN       NaN        NaN        NaN       0  
2016-01-05        NaN        NaN       NaN        NaN        NaN       0  
2016-01-06        NaN        NaN       NaN        NaN        NaN       0  
2016-01-07        NaN        NaN       NaN        NaN        NaN       1  
2016-01-08        NaN        NaN       NaN        NaN        NaN       0  
...               ...        ...       ...        ...        ...     ...  
2021-11-15  86.975383  86.280765 -0.077363  57.778570 -30.767687       1  
2021-11-16  97.397636  88.443502 -0.073960  65.696857  -2.602364       0  
2021-11-17  89.387056  91.253358 -0.070285  67.084202  -7.636080       0  
2021-11-18  20.359988  69.048227 -0.066757  62.814885 -33.742134       0  
2021-11-19  24.372689  44.706578 -0.063657  56.756723 -55.058642       0  

[1449 rows x 38 columns]

In [892]:
hsi_ti = hsi_ti.dropna()
X = hsi_ti.drop("Target", axis=1)  # Feature Matrix
y = hsi_ti["Target"]               # Target Variable

In [893]:
model = LinearRegression()

#Initializing RFE model
rfe = RFE(model, n_features_to_select=7)

#Transforming data using RFE
X_rfe = rfe.fit_transform(X,y)  

#Fitting the data to model
model.fit(X_rfe,y)

print(rfe.support_)
print(rfe.ranking_)

[False False False False False False False False False False False False
  True False False  True False False False False  True False False  True
 False  True False False False False False False False False  True False
  True]
[19 28 30 20 31 17  2  3  6 21 11 25  1  8 13  1 12 24 16  4  1 23 29  1
 22  1 15 26 27 14  7  5 18  9  1 10  1]


In [894]:
# no. of features
#
nof_list = np.arange(1, 13)            
high_score = 0

# Variable to store the optimum features
#
nof = 0           
score_list = []

for n in range(len(nof_list)):
    X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.9, random_state = 0)

    model = LinearRegression()
    rfe = RFE(model, n_features_to_select=nof_list[n])
    X_train_rfe = rfe.fit_transform(X_train,y_train)
    X_test_rfe = rfe.transform(X_test)
    model.fit(X_train_rfe,y_train)

    score = model.score(X_test_rfe,y_test)
    score_list.append(score)

    if(score > high_score):
        high_score = score
        nof = nof_list[n]

print("Optimum number of features: %d" % nof)
print("Score with %d features: %f" % (nof, high_score))

Optimum number of features: 0
Score with 0 features: 0.000000


In [847]:
cols = list(X.columns)
model = LinearRegression()

# Initializing RFE model
rfe = RFE(model, n_features_to_select=10)             

# Transforming data using RFE
X_rfe = rfe.fit_transform(X,y)  

# Fitting the data to model
model.fit(X_rfe,y)              
temp = pd.Series(rfe.support_, index = cols)
selected_features_rfe = temp[temp==True].index

print(selected_features_rfe)

Index(['ADX', 'BOP', 'DX', 'MFI', 'MINUS_DI', 'PLUS_DI', 'PPO', 'ROC',
       'ROCR100', 'TRIX'],
      dtype='object')


<h2>จากการทำ Feature Selection ควรจะใช้ 'ADX', 'BOP', 'DX', 'MFI', 'MINUS_DI', 'PLUS_DI', 'PPO', 'ROC',
       'ROCR100', 'TRIX'ในการสร้าง model</h2>

In [920]:
X = hsi_ti.loc[:, ['ADX', 'BOP', 'DX', 'MFI', 'MINUS_DI', 'PLUS_DI', 'PPO', 'ROC','ROCR100', 'TRIX']].values
#X = dji_ti.loc[:, ['CCI', 'DX', 'MINUS_DI', 'PLUS_DM', 'slowd']].values
y = hsi_ti.loc[:, ['Target']].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [921]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

<h2>Decision Tree</h2>

In [922]:
dtc = DecisionTreeClassifier()
dtc.fit(X_train, y_train)

DecisionTreeClassifier()

In [923]:
# Prediction
#
y_pred = dtc.predict(X_test)  #Accuracy
y_pred

array([0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 0])

In [924]:
# Look at the actual y_test
#
y_test

array([[0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
    

In [925]:
# See the accuracy
#
from sklearn import metrics
print('Accuracy Score:', metrics.accuracy_score(y_test, y_pred))

Accuracy Score: 0.456


In [926]:
# See the confusion matrix
#
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[43, 74],
       [62, 71]])

<h2>Random Forest</h2>

<h2>Logistic Regression</h2>

<h2>XGBoost</h2>

<h2>Linear Regression</h2>

<h2>Gauccian Process Regression</h2>

<h1>SSE Composite Index</h1>

<h2>Feature Selection</h2>

In [934]:
sse['Future Close'] = sse['Close'].shift(-1)
sse

High          Low         Open        Close      Volume  \
Date                                                                         
2016-01-04  3538.688965  3295.740967  3536.589111  3296.258057      184400   
2016-01-05  3328.138916  3189.604980  3196.650879  3287.710938      266900   
2016-01-06  3362.974121  3288.933105  3291.195068  3361.840088      238900   
2016-01-07  3309.656982  3115.885010  3309.656982  3125.001953       70600   
2016-01-08  3235.450928  3056.877930  3194.625000  3186.412109      286400   
...                 ...          ...          ...          ...         ...   
2021-11-17  3537.510010  3513.520020  3518.560059  3537.370117      276700   
2021-11-18  3537.979980  3513.110107  3531.489990  3520.709961      312400   
2021-11-19  3561.909912  3517.649902  3519.280029  3560.370117      318000   
2021-11-22  3585.187988  3562.750977  3562.762939  3582.080078      330000   
2021-11-23  3598.375000  3577.360840  3580.505859  3589.089355  1641420932   

              Adj Close  Future Close  
Date                                   
2016-01-04  3296.258057   3287.710938  
2016-01-05  3287.710938   3361.840088  
2016-01-06  3361.840088   3125.001953  
2016-01-07  3125.001953   3186.412109  
2016-01-08  3186.412109   3016.704102  
...                 ...           ...  
2021-11-17  3537.370117   3520.709961  
2021-11-18  3520.709961   3560.370117  
2021-11-19  3560.370117   3582.080078  
2021-11-22  3582.080078   3589.089355  
2021-11-23  3589.089355           NaN  

[1431 rows x 7 columns]

In [935]:
target = computeTarget(sse['Close'], sse['Future Close'])

sse['Target'] = target
sse_target = sse.loc[hsi.index[-1]]
sse = sse.dropna()

In [936]:
close = sse['Close']
high = sse['High']
low = sse['Low']
open = sse['Open']
volume  = sse['Volume']

In [937]:
sse_ti = pd.DataFrame()
sse_ti['SMA20'] = talib.SMA(close, timeperiod=20)
sse_ti['SMA50'] = talib.SMA(close, timeperiod=50)
sse_ti['SMA200'] = talib.SMA(close, timeperiod=200)
sse_ti['EMA'] = talib.EMA(close, timeperiod=14)
sse_ti['OBV'] = talib.OBV(close, volume)
sse_ti['RSI14'] = talib.RSI(close, timeperiod=14)
sse_ti['ADX'] = talib.ADX(high, low, close, timeperiod=14)
sse_ti['ADXR'] = talib.ADXR(high, low, close, timeperiod=14)
sse_ti['aroondown'], sse_ti['aroonup'] = talib.AROON(high, low, timeperiod=14)
sse_ti['APO'] = talib.APO(close, fastperiod=12, slowperiod=26, matype=0)
sse_ti['AROONOSC'] = talib.AROONOSC(high, low, timeperiod=14)
sse_ti['BOP'] = talib.BOP(open, high, low, close)
sse_ti['CCI'] = talib.CCI(high, low, close, timeperiod=14)
sse_ti['CMO'] = talib.CMO(close, timeperiod=14)
sse_ti['DX'] = talib.DX(high, low, close, timeperiod=14)
sse_ti['macd'],sse_ti['macdsignal'],sse_ti['macdhist'] = talib.MACD(close, fastperiod = 12, slowperiod=26, signalperiod=9)
sse_ti['MFI'] = talib.MFI(high, low, close, volume, timeperiod=14)
sse_ti['MINUS_DI'] = talib.MINUS_DI(high, low, close, timeperiod=14)
sse_ti['MINUS_DM'] = talib.MINUS_DM(high, low, timeperiod=14)
sse_ti['MOM'] = talib.MOM(close, timeperiod=14)
sse_ti['PLUS_DI'] = talib.PLUS_DI(high, low, close, timeperiod=14)
sse_ti['PLUS_DM'] = talib.PLUS_DM(high, low, timeperiod=14)
sse_ti['PPO'] = talib.PPO(close, fastperiod=12, slowperiod=26, matype=0)
sse_ti['ROC'] = talib.ROC(close, timeperiod=10)
sse_ti['ROCP'] = talib.ROCP(close, timeperiod=10)
sse_ti['ROCR'] = talib.ROCR(close, timeperiod=10)
sse_ti['ROCR100'] = talib.ROCR100(close, timeperiod=10)
sse_ti['slowk'], sse_ti['slowd'] = talib.STOCH(high, low, close, fastk_period=5, slowk_period=3, slowd_period=3, slowd_matype=0)
sse_ti['fastk'], sse_ti['fastd'] = talib.STOCHF(high, low, close, fastk_period=5, fastd_period=3, fastd_matype=0)
sse_ti['TRIX'] = talib.TRIX(close, timeperiod=30)
sse_ti['ULTOSC'] = talib.ULTOSC(high, low, close, timeperiod1=7, timeperiod2=14, timeperiod3=28)
sse_ti['WILLR'] = talib.WILLR(high, low, close, timeperiod=14)
sse_ti['Target'] = sse['Target']
sse_ti

SMA20        SMA50       SMA200          EMA         OBV  \
Date                                                                         
2016-01-04          NaN          NaN          NaN          NaN    184400.0   
2016-01-05          NaN          NaN          NaN          NaN    -82500.0   
2016-01-06          NaN          NaN          NaN          NaN    156400.0   
2016-01-07          NaN          NaN          NaN          NaN     85800.0   
2016-01-08          NaN          NaN          NaN          NaN    372200.0   
...                 ...          ...          ...          ...         ...   
2021-11-16  3539.605518  3579.860229  3527.289161  3528.458933  24156100.0   
2021-11-17  3537.124023  3580.044614  3526.994912  3529.647091  24432800.0   
2021-11-18  3533.420520  3579.580015  3526.766562  3528.455474  24120400.0   
2021-11-19  3532.309021  3579.445415  3526.652953  3532.710760  24438400.0   
2021-11-22  3530.920020  3579.146216  3526.457034  3539.293335  24768400.0   

                RSI14        ADX       ADXR  aroondown     aroonup  ...  \
Date                                                                ...   
2016-01-04        NaN        NaN        NaN        NaN         NaN  ...   
2016-01-05        NaN        NaN        NaN        NaN         NaN  ...   
2016-01-06        NaN        NaN        NaN        NaN         NaN  ...   
2016-01-07        NaN        NaN        NaN        NaN         NaN  ...   
2016-01-08        NaN        NaN        NaN        NaN         NaN  ...   
...               ...        ...        ...        ...         ...  ...   
2021-11-16  45.870457  25.622516  22.424765  71.428571    0.000000  ...   
2021-11-17  49.067261  25.210056  22.776071  64.285714   21.428571  ...   
2021-11-18  45.942678  24.807825  22.922670  57.142857   14.285714  ...   
2021-11-19  53.529165  23.497480  22.955213  50.000000  100.000000  ...   
2021-11-22  57.080036  22.141173  22.915652  42.857143  100.000000  ...   

                ROCR     ROCR100      slowk      slowd      fastk      fastd  \
Date                                                                           
2016-01-04       NaN         NaN        NaN        NaN        NaN        NaN   
2016-01-05       NaN         NaN        NaN        NaN        NaN        NaN   
2016-01-06       NaN         NaN        NaN        NaN        NaN        NaN   
2016-01-07       NaN         NaN        NaN        NaN        NaN        NaN   
2016-01-08       NaN         NaN        NaN        NaN        NaN        NaN   
...              ...         ...        ...        ...        ...        ...   
2021-11-16  1.004610  100.460977  83.443113  86.227132  71.911860  83.443113   
2021-11-17  1.011099  101.109894  78.592268  84.764400  80.668761  78.592268   
2021-11-18  0.998253   99.825336  57.646427  73.227269  20.358659  57.646427   
2021-11-19  1.019705  101.970462  65.957363  67.398686  96.844670  65.957363   
2021-11-22  1.023852  102.385225  70.963817  64.855869  95.688122  70.963817   

                TRIX     ULTOSC      WILLR  Target  
Date                                                
2016-01-04       NaN        NaN        NaN       0  
2016-01-05       NaN        NaN        NaN       1  
2016-01-06       NaN        NaN        NaN       0  
2016-01-07       NaN        NaN        NaN       1  
2016-01-08       NaN        NaN        NaN       0  
...              ...        ...        ...     ...  
2021-11-16 -0.000020  61.270883 -33.685900       1  
2021-11-17 -0.002265  65.254481 -19.600317       0  
2021-11-18 -0.004395  61.566902 -34.662373       1  
2021-11-19 -0.006107  64.791843  -1.357007       1  
2021-11-22 -0.007290  63.482566  -2.272727       1  

[1430 rows x 38 columns]

In [941]:
sse_ti = sse_ti.dropna()
X = sse_ti.drop("Target", axis=1)  # Feature Matrix
y = sse_ti["Target"]               # Target Variable

In [942]:
model = LinearRegression()

#Initializing RFE model
rfe = RFE(model, n_features_to_select=7)

#Transforming data using RFE
X_rfe = rfe.fit_transform(X,y)  

#Fitting the data to model
model.fit(X_rfe,y)

print(rfe.support_)
print(rfe.ranking_)

[ True False False  True False False False False False False False False
  True False False False False False  True False False False False False
 False  True False False False  True False False False False  True False
 False]
[ 1 23 28  1 31 14 11 27 25 20  3 22  1 19 12 17  5  8  1 10 15 26 24  4
 13  1  6 29 30  1 18  2 21  9  1 16  7]


In [943]:
# no. of features
#
nof_list = np.arange(1, 13)            
high_score = 0

# Variable to store the optimum features
#
nof = 0           
score_list = []

for n in range(len(nof_list)):
    X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.9, random_state = 0)

    model = LinearRegression()
    rfe = RFE(model, n_features_to_select=nof_list[n])
    X_train_rfe = rfe.fit_transform(X_train,y_train)
    X_test_rfe = rfe.transform(X_test)
    model.fit(X_train_rfe,y_train)

    score = model.score(X_test_rfe,y_test)
    score_list.append(score)

    if(score > high_score):
        high_score = score
        nof = nof_list[n]

print("Optimum number of features: %d" % nof)
print("Score with %d features: %f" % (nof, high_score))

Optimum number of features: 0
Score with 0 features: 0.000000


In [944]:
cols = list(X.columns)
model = LinearRegression()

# Initializing RFE model
rfe = RFE(model, n_features_to_select=10)             

# Transforming data using RFE
X_rfe = rfe.fit_transform(X,y)  

# Fitting the data to model
model.fit(X_rfe,y)              
temp = pd.Series(rfe.support_, index = cols)
selected_features_rfe = temp[temp==True].index

print(selected_features_rfe)

Index(['SMA20', 'EMA', 'APO', 'BOP', 'macdhist', 'PLUS_DI', 'PPO', 'ROCR100',
       'slowd', 'TRIX'],
      dtype='object')


<h2>จากการทำ Feature Selection ควรจะใช้ 'ADX', 'ADXR', 'BOP', 'DX', 'MFI', 'MINUS_DI', 'PLUS_DI', 'PPO', 'TRIX',
       'WILLR'ในการสร้าง model</h2>

In [945]:
X = sse_ti.loc[:, ['ADX', 'ADXR', 'BOP', 'DX', 'MFI', 'MINUS_DI', 'PLUS_DI', 'PPO', 'TRIX','WILLR']].values
#X = dji_ti.loc[:, ['CCI', 'DX', 'MINUS_DI', 'PLUS_DM', 'slowd']].values
y = sse_ti.loc[:, ['Target']].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [946]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

<h2>Decision Tree</h2>

In [947]:
dtc = DecisionTreeClassifier()
dtc.fit(X_train, y_train)

DecisionTreeClassifier()

In [948]:
# Prediction
#
y_pred = dtc.predict(X_test)  #Accuracy
y_pred

array([0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 1, 0])

In [949]:
# Look at the actual y_test
#
y_test

array([[1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
    

In [950]:
# See the accuracy
#
from sklearn import metrics
print('Accuracy Score:', metrics.accuracy_score(y_test, y_pred))

Accuracy Score: 0.47368421052631576


In [951]:
# See the confusion matrix
#
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[59, 55],
       [75, 58]])

<h2>Random Forest</h2>

<h2>Logistic Regression</h2>

<h2>XGBoost</h2>

<h2>Linear Regression</h2>

<h2>Gauccian Process Regression</h2>